DROP DATABASE IF EXISTS GOOD_FOOD;
CREATE DATABASE GOOD_FOOD;
USE GOOD_FOOD;

CREATE TABLE HINH_ANH (
	ID INT NOT NULL IDENTITY(1,1),
	CONTEXT VARCHAR(MAX),
	EXTENSION VARCHAR(250),
	PRIMARY KEY (ID),
);

CREATE TABLE NGUOI_DUNG (
	ID INT NOT NULL IDENTITY(1,1),
	HO_VA_TEN VARCHAR(250),
	TEN_DANG_NHAP VARCHAR(250),
	SO_DIEN_THOAI VARCHAR(250),
	NGAY_SINH DATE,
	MAT_KHAU VARCHAR(250),
	EMAIL VARCHAR(250),
	GIOI_TINH VARCHAR(250),
	ID_HINH_ANH INT,
	LOAI_NGUOI_DUNG VARCHAR(250),
	PRIMARY KEY (ID),
	FOREIGN KEY (ID_HINH_ANH) REFERENCES HINH_ANH(ID),
);

CREATE TABLE DIA_CHI (
	ID INT NOT NULL IDENTITY(1,1),
	SO_NHA VARCHAR(250),
	DUONG VARCHAR(250),
	PHUONG_XA VARCHAR(250),
	QUAN_HUYEN VARCHAR(250),
	TINH_THANH_PHO VARCHAR(250),
	PRIMARY KEY (ID),
);

CREATE TABLE QUAN_AN (
	ID INT NOT NULL IDENTITY(1,1),
	TEN_QUAN_AN VARCHAR(250),
	NHAN_XET VARCHAR(250),
	CHAT_LUONG VARCHAR(250),
	THOI_GIAN_HOAT_DONG VARCHAR(250),
	SO_DIEN_THOAI VARCHAR(250),
	ID_DIA_CHI INT,
	ID_HINH_ANH INT,
	DA_DUYET BIT,
	ID_NGUOI_SO_HUU INT,
	PRIMARY KEY (ID),
	FOREIGN KEY (ID_DIA_CHI) REFERENCES DIA_CHI(ID),
	FOREIGN KEY (ID_HINH_ANH) REFERENCES HINH_ANH(ID),
	FOREIGN KEY (ID_NGUOI_SO_HUU) REFERENCES NGUOI_DUNG(ID)
);

CREATE TABLE BAI_VIET (
	ID INT NOT NULL IDENTITY(1,1),
	THOI_GIAN DATETIME,
	ID_QUAN_AN INT,
	ID_HINH_ANH_QUAN_AN INT,
	ID_NGUOI_DUNG INT,
	NHAN_XET VARCHAR(250),
	VE_SINH VARCHAR(250),
	HUONG_VI VARCHAR(250),
	KHONG_GIAN VARCHAR(250),
	GIA_CA FLOAT,
	PHUC_VU VARCHAR(250),
	PRIMARY KEY (ID),
	FOREIGN KEY (ID_QUAN_AN) REFERENCES QUAN_AN(ID),
	FOREIGN KEY (ID_HINH_ANH_QUAN_AN) REFERENCES HINH_ANH(ID),
	FOREIGN KEY (ID_NGUOI_DUNG) REFERENCES NGUOI_DUNG(ID)
);

CREATE TABLE BAO_CAO (
	ID INT NOT NULL IDENTITY(1,1),
	LOAI_BAO_CAO VARCHAR(250),
	ID_BAI_VIET INT,
	PRIMARY KEY (ID),
	FOREIGN KEY (ID_BAI_VIET) REFERENCES BAI_VIET(ID),
);

CREATE TABLE DANH_SACH_YEU_THICH (
	ID INT NOT NULL IDENTITY(1,1),
    	ID_NGUOI_DUNG INT,
    	PRIMARY KEY (ID),
	FOREIGN KEY (ID_NGUOI_DUNG) REFERENCES NGUOI_DUNG(ID),
);

CREATE TABLE BAI_VIET_THUOC_DANH_SACH_YEU_THICH (
	ID_BAI_VIET INT,
	ID_DANH_SACH INT,
   	FOREIGN KEY (ID_BAI_VIET) REFERENCES BAI_VIET(ID),
	FOREIGN KEY (ID_DANH_SACH) REFERENCES DANH_SACH_YEU_THICH(ID)
);

CREATE TABLE THONG_BAO (
	ID INT NOT NULL IDENTITY(1,1),
	THOI_GIAN DATETIME,
	NOI_DUNG VARCHAR(250),
	ID_NGUOI_DUNG INT,
	PRIMARY KEY (ID),
	FOREIGN KEY (ID_NGUOI_DUNG) REFERENCES NGUOI_DUNG(ID)
);

CREATE TABLE THEO_DOI (
	ID_NGUOI_DUNG_THEO_DOI INT,
	ID_NGUOI_DUNG_DUOC_THEO_DOI INT,
	FOREIGN KEY (ID_NGUOI_DUNG_THEO_DOI) REFERENCES NGUOI_DUNG(ID),
	FOREIGN KEY (ID_NGUOI_DUNG_DUOC_THEO_DOI) REFERENCES NGUOI_DUNG(ID)
);

CREATE TABLE MON_AN (
	ID INT NOT NULL IDENTITY(1,1),
	NHAN_XET VARCHAR(250),
	CHAT_LUONG FLOAT,
	GIA_TIEN INT,
	ID_QUAN_AN INT,
	ID_HINH_ANH INT,
	PRIMARY KEY (ID),
	FOREIGN KEY (ID_QUAN_AN) REFERENCES QUAN_AN(ID),
	FOREIGN KEY (ID_HINH_ANH) REFERENCES HINH_ANH(ID)
);

CREATE TABLE BAI_VIET_CO_MON_AN (
	ID_BAI_VIET INT,
	ID_MON_AN INT,
	ID_HINH_ANH INT,
	NHAN_XET VARCHAR(250),
	DANH_GIA FLOAT,
	FOREIGN KEY (ID_BAI_VIET) REFERENCES BAI_VIET(ID),
	FOREIGN KEY (ID_MON_AN) REFERENCES MON_AN(ID),
	FOREIGN KEY (ID_HINH_ANH) REFERENCES HINH_ANH(ID)
);

CREATE TABLE BINH_LUAN (
	ID INT NOT NULL IDENTITY(1,1),
	THOI_GIAN DATETIME,
	NOI_DUNG VARCHAR(250),
	ID_BAI_VIET INT,
	ID_NGUOI_DUNG INT,
	PRIMARY KEY (ID),
	FOREIGN KEY (ID_BAI_VIET) REFERENCES BAI_VIET(ID),
	FOREIGN KEY (ID_NGUOI_DUNG) REFERENCES NGUOI_DUNG(ID),
);

CREATE TABLE DANH_GIA_BAI_VIET (
	ID_BAI_VIET INT,
	ID_NGUOI_DUNG INT,
	LOAI_DANH_GIA BIT,
	FOREIGN KEY (ID_BAI_VIET) REFERENCES BAI_VIET(ID),
	FOREIGN KEY (ID_NGUOI_DUNG) REFERENCES NGUOI_DUNG(ID)
);

CREATE TABLE CUOC_TRO_CHUYEN (
	ID INT NOT NULL IDENTITY(1,1),
	ID_NGUOI_DUNG_1 INT,
	ID_NGUOI_DUNG_2 INT,
	THONG_BAO BIT,
	CHAN BIT,
	PRIMARY KEY (ID),
	FOREIGN KEY (ID_NGUOI_DUNG_1) REFERENCES NGUOI_DUNG(ID),
	FOREIGN KEY (ID_NGUOI_DUNG_2) REFERENCES NGUOI_DUNG(ID)
);

CREATE TABLE THE_LOAI (
	ID INT NOT NULL IDENTITY(1,1),
	TEN_THE_LOAI VARCHAR(250),
	PRIMARY KEY (ID),
);

CREATE TABLE THE_LOAI_MON_AN (
	ID INT NOT NULL IDENTITY(1,1),
	ID_THE_LOAI INT,
	ID_MON_AN INT,
	PRIMARY KEY (ID),
	FOREIGN KEY (ID_THE_LOAI) REFERENCES THE_LOAI(ID),
	FOREIGN KEY (ID_MON_AN) REFERENCES MON_AN(ID)
);

CREATE TABLE TIN_NHAN (
	ID INT NOT NULL IDENTITY(1,1),
	ID_CUOC_TRO_CHUYEN INT,
	THOI_GIAN DATETIME,
	NOI_DUNG VARCHAR(250),
	CUA_USER_NAO BIT,
	PRIMARY KEY (ID),
	FOREIGN KEY (ID_CUOC_TRO_CHUYEN) REFERENCES CUOC_TRO_CHUYEN(ID)
);

CREATE TABLE DU_LIEU_DE_XUAT (
	ID INT NOT NULL IDENTITY(1,1),
	ID_NGUOI_DUNG INT,
	ID_THE_LOAI INT,
	MOC_THOI_GIAN VARCHAR(250),
	PRIMARY KEY (ID),
	FOREIGN KEY (ID_NGUOI_DUNG) REFERENCES NGUOI_DUNG(ID),
	FOREIGN KEY (ID_THE_LOAI) REFERENCES THE_LOAI(ID),
);

INSERT INTO HINH_ANH (CONTEXT, EXTENSION) VALUES (NULL, 'JPG');
INSERT INTO HINH_ANH (CONTEXT, EXTENSION) VALUES (NULL, 'JPG');
INSERT INTO HINH_ANH (CONTEXT, EXTENSION) VALUES (NULL, 'JPG');

INSERT INTO NGUOI_DUNG (HO_VA_TEN, TEN_DANG_NHAP, SO_DIEN_THOAI, NGAY_SINH,
MAT_KHAU, EMAIL, GIOI_TINH, ID_HINH_ANH, LOAI_NGUOI_DUNG) 
VALUES ('Nguyen Minh Nghia', 'nghianguyen', '0901112223', '2001-03-03',
'123456', 'nghianguyen@gmail.com', 'Nam', 1, 'Nguoi dung lau nam');

INSERT INTO NGUOI_DUNG (HO_VA_TEN, TEN_DANG_NHAP, SO_DIEN_THOAI, NGAY_SINH,
MAT_KHAU, EMAIL, GIOI_TINH, ID_HINH_ANH, LOAI_NGUOI_DUNG) 
VALUES ('Nguyen Thuy Ngoc', 'ngocnguyen', '0903334445', '2001-06-06',
'123456', 'ngocnguyen@gmail.com', 'Nu', 2, 'Nguoi dung co tham nien');

INSERT INTO NGUOI_DUNG (HO_VA_TEN, TEN_DANG_NHAP, SO_DIEN_THOAI, NGAY_SINH,
MAT_KHAU, EMAIL, GIOI_TINH, ID_HINH_ANH, LOAI_NGUOI_DUNG) 
VALUES ('Tran Pham Thai Hoa', 'hoatran', '0905556667', '2001-09-09',
'123456', 'hoatran@gmail.com', 'Nam', 3, 'Nguoi dung tap su');

INSERT INTO DIA_CHI (SO_NHA, DUONG, PHUONG_XA, QUAN_HUYEN, TINH_THANH_PHO) 
VALUES ('33', 'Cach mang thang Tam', '1', '3', 'TPHCM');

INSERT INTO DIA_CHI (SO_NHA, DUONG, PHUONG_XA, QUAN_HUYEN, TINH_THANH_PHO) 
VALUES ('66', 'Tran Duy Hung', '2', '6', 'Ha Noi');

INSERT INTO DIA_CHI (SO_NHA, DUONG, PHUONG_XA, QUAN_HUYEN, TINH_THANH_PHO) 
VALUES ('99', 'Cong Hoa', '13', 'Tan Binh', 'TPHCM');

INSERT INTO QUAN_AN (TEN_QUAN_AN, NHAN_XET, CHAT_LUONG, THOI_GIAN_HOAT_DONG,
SO_DIEN_THOAI, ID_DIA_CHI, ID_HINH_ANH, DA_DUYET, ID_NGUOI_SO_HUU) 
VALUES ('Papa xot', 'do an ngon nhung cho lau', '4 sao', '8h toi 22h',
'0123456789', 1, 1, 1, 1);

INSERT INTO QUAN_AN (TEN_QUAN_AN, NHAN_XET, CHAT_LUONG, THOI_GIAN_HOAT_DONG,
SO_DIEN_THOAI, ID_DIA_CHI, ID_HINH_ANH, DA_DUYET, ID_NGUOI_SO_HUU) 
VALUES ('Ngo Quyen', 'com ngon nhung nhieu dau', '4.5 sao', '8h toi 22h',
'0123789456', 2, 2, 1, 2);

INSERT INTO QUAN_AN (TEN_QUAN_AN, NHAN_XET, CHAT_LUONG, THOI_GIAN_HOAT_DONG,
SO_DIEN_THOAI, ID_DIA_CHI, ID_HINH_ANH, DA_DUYET, ID_NGUOI_SO_HUU) 
VALUES ('Bach Dan', 'do an ngon va gia hop ly', '5 sao', '8h toi 22h',
'0789456123', 3, 3, 1, 3);

INSERT INTO BAI_VIET (THOI_GIAN, ID_QUAN_AN, ID_HINH_ANH_QUAN_AN, ID_NGUOI_DUNG,
NHAN_XET, VE_SINH, HUONG_VI, KHONG_GIAN, GIA_CA, PHUC_VU) 
VALUES ('2023-02-01 11:00:00', 1, 1, 1, 'nhan xet bai viet 1', 'tot', 'tot', 'rong rai', 50000, 'chu dao');


INSERT INTO BAI_VIET (THOI_GIAN, ID_QUAN_AN, ID_HINH_ANH_QUAN_AN, ID_NGUOI_DUNG,
NHAN_XET, VE_SINH, HUONG_VI, KHONG_GIAN, GIA_CA, PHUC_VU) 
VALUES ('2023-02-01 12:00:00', 2, 2, 2, 'nhan xet bai viet 1', 'tot', 'tot', 'rong rai', 30000, 'chu dao');


INSERT INTO BAI_VIET (THOI_GIAN, ID_QUAN_AN, ID_HINH_ANH_QUAN_AN, ID_NGUOI_DUNG,
NHAN_XET, VE_SINH, HUONG_VI, KHONG_GIAN, GIA_CA, PHUC_VU) 
VALUES ('2023-02-01 13:00:00', 3, 3, 3, 'nhan xet bai viet 1', 'tot', 'tot', 'rong rai', 40000, 'chu dao');

INSERT INTO BAO_CAO (LOAI_BAO_CAO, ID_BAI_VIET) VALUES ('Spam', 1);
INSERT INTO BAO_CAO (LOAI_BAO_CAO, ID_BAI_VIET) VALUES ('Sai su that', 2);
INSERT INTO BAO_CAO (LOAI_BAO_CAO, ID_BAI_VIET) VALUES ('Noi dung khong phu hop', 3);

INSERT INTO DANH_SACH_YEU_THICH (ID_NGUOI_DUNG) VALUES (1);
INSERT INTO DANH_SACH_YEU_THICH (ID_NGUOI_DUNG) VALUES (2);
INSERT INTO DANH_SACH_YEU_THICH (ID_NGUOI_DUNG) VALUES (3);

INSERT INTO BAI_VIET_THUOC_DANH_SACH_YEU_THICH (ID_BAI_VIET, ID_DANH_SACH) VALUES (1, 2);
INSERT INTO BAI_VIET_THUOC_DANH_SACH_YEU_THICH (ID_BAI_VIET, ID_DANH_SACH) VALUES (2, 3);
INSERT INTO BAI_VIET_THUOC_DANH_SACH_YEU_THICH (ID_BAI_VIET, ID_DANH_SACH) VALUES (3, 1);

INSERT INTO THONG_BAO (THOI_GIAN, NOI_DUNG, ID_NGUOI_DUNG)
VALUES ('2023-02-01 14:00:00', 'Thong bao nguoi dung 1', 1);

INSERT INTO THONG_BAO (THOI_GIAN, NOI_DUNG, ID_NGUOI_DUNG)
VALUES ('2023-02-01 15:00:00', 'Thong bao nguoi dung 2', 2);

INSERT INTO THONG_BAO (THOI_GIAN, NOI_DUNG, ID_NGUOI_DUNG)
VALUES ('2023-02-01 16:00:00', 'Thong bao nguoi dung 3', 3);

INSERT INTO THEO_DOI (ID_NGUOI_DUNG_THEO_DOI, ID_NGUOI_DUNG_DUOC_THEO_DOI) 
VALUES (1, 2);

INSERT INTO THEO_DOI (ID_NGUOI_DUNG_THEO_DOI, ID_NGUOI_DUNG_DUOC_THEO_DOI) 
VALUES (2, 3);

INSERT INTO THEO_DOI (ID_NGUOI_DUNG_THEO_DOI, ID_NGUOI_DUNG_DUOC_THEO_DOI) 
VALUES (3, 1);

INSERT INTO MON_AN (NHAN_XET, CHAT_LUONG, GIA_TIEN, ID_QUAN_AN, ID_HINH_ANH) 
VALUES ('ngon', 5, 50000, 1, 1);

INSERT INTO MON_AN (NHAN_XET, CHAT_LUONG, GIA_TIEN, ID_QUAN_AN, ID_HINH_ANH) 
VALUES ('do', 1, 40000, 2, 2);

INSERT INTO MON_AN (NHAN_XET, CHAT_LUONG, GIA_TIEN, ID_QUAN_AN, ID_HINH_ANH) 
VALUES ('ngon', 4, 70000, 3, 3);

INSERT INTO BAI_VIET_CO_MON_AN (ID_BAI_VIET, ID_MON_AN, ID_HINH_ANH,
NHAN_XET, DANH_GIA) VALUES (1, 1, 1, 'nhan xet', 4.5);

INSERT INTO BAI_VIET_CO_MON_AN (ID_BAI_VIET, ID_MON_AN, ID_HINH_ANH,
NHAN_XET, DANH_GIA) VALUES (2, 2, 2, 'nhan xet', 3.5);

INSERT INTO BAI_VIET_CO_MON_AN (ID_BAI_VIET, ID_MON_AN, ID_HINH_ANH,
NHAN_XET, DANH_GIA) VALUES (3, 3, 3, 'nhan xet', 5.0);

INSERT INTO BINH_LUAN (THOI_GIAN, NOI_DUNG, ID_BAI_VIET, ID_NGUOI_DUNG) 
VALUES ('2023-02-01 17:00:00', 'binh luan', 1, 1);

INSERT INTO BINH_LUAN (THOI_GIAN, NOI_DUNG, ID_BAI_VIET, ID_NGUOI_DUNG) 
VALUES ('2023-02-01 18:00:00', 'binh luan', 2, 2);

INSERT INTO BINH_LUAN (THOI_GIAN, NOI_DUNG, ID_BAI_VIET, ID_NGUOI_DUNG) 
VALUES ('2023-02-01 19:00:00', 'binh luan', 3, 3);

INSERT INTO DANH_GIA_BAI_VIET (ID_BAI_VIET, ID_NGUOI_DUNG, LOAI_DANH_GIA) 
VALUES (1, 1, 1);

INSERT INTO DANH_GIA_BAI_VIET (ID_BAI_VIET, ID_NGUOI_DUNG, LOAI_DANH_GIA) 
VALUES (2, 2, 0);

INSERT INTO DANH_GIA_BAI_VIET (ID_BAI_VIET, ID_NGUOI_DUNG, LOAI_DANH_GIA) 
VALUES (3, 3, 1);

INSERT INTO CUOC_TRO_CHUYEN (ID_NGUOI_DUNG_1, ID_NGUOI_DUNG_2, THONG_BAO, CHAN) 
VALUES (1, 2, 1, 0);

INSERT INTO CUOC_TRO_CHUYEN (ID_NGUOI_DUNG_1, ID_NGUOI_DUNG_2, THONG_BAO, CHAN) 
VALUES (2, 3, 0, 0);

INSERT INTO CUOC_TRO_CHUYEN (ID_NGUOI_DUNG_1, ID_NGUOI_DUNG_2, THONG_BAO, CHAN) 
VALUES (3, 1, 1, 1);

INSERT INTO THE_LOAI (TEN_THE_LOAI) VALUES ('Mon Han');
INSERT INTO THE_LOAI (TEN_THE_LOAI) VALUES ('Mon Nhat');
INSERT INTO THE_LOAI (TEN_THE_LOAI) VALUES ('Mon Au');

INSERT INTO THE_LOAI_MON_AN (ID_THE_LOAI, ID_MON_AN) VALUES (1, 1);
INSERT INTO THE_LOAI_MON_AN (ID_THE_LOAI, ID_MON_AN) VALUES (2, 2);
INSERT INTO THE_LOAI_MON_AN (ID_THE_LOAI, ID_MON_AN) VALUES (3, 3);

INSERT INTO TIN_NHAN (ID_CUOC_TRO_CHUYEN, THOI_GIAN, NOI_DUNG, CUA_USER_NAO) 
VALUES (1, '2023-02-01 20:00:00', 'test tro chuyen 1', 0);

INSERT INTO TIN_NHAN (ID_CUOC_TRO_CHUYEN, THOI_GIAN, NOI_DUNG, CUA_USER_NAO) 
VALUES (2, '2023-02-01 21:00:00', 'test tro chuyen 2', 1);

INSERT INTO TIN_NHAN (ID_CUOC_TRO_CHUYEN, THOI_GIAN, NOI_DUNG, CUA_USER_NAO) 
VALUES (3, '2023-02-01 22:00:00', 'test tro chuyen 3', 0);

INSERT INTO DU_LIEU_DE_XUAT (ID_NGUOI_DUNG, ID_THE_LOAI, MOC_THOI_GIAN) 
VALUES (1, 1, 'moc thoi gian 1');

INSERT INTO DU_LIEU_DE_XUAT (ID_NGUOI_DUNG, ID_THE_LOAI, MOC_THOI_GIAN) 
VALUES (2, 2, 'moc thoi gian 2');

INSERT INTO DU_LIEU_DE_XUAT (ID_NGUOI_DUNG, ID_THE_LOAI, MOC_THOI_GIAN) 
VALUES (3, 3, 'moc thoi gian 3');